package Test.factory;

import uflow.data.base.DataItem;
import uflow.data.common.immutable.Bool;
import uflow.data.common.immutable.Result;
import uflow.data.common.modifier.ListModifier;
import uflow.data.common.modifier.MapModifier;
import uflow.data.function.modifier.*;
import uflow.data.input.immutable.CheckboxInput;
import uflow.data.input.immutable.DropdownInput;
import uflow.data.input.immutable.RadioInput;
import uflow.data.input.immutable.TextInput;
import uflow.data.input.modifier.FormModifier;
import uflow.data.model.immutable.ProcessModel;
import uflow.data.model.modifier.*;

/**
 * Created by Signum+ Software GmbH
 * Author: Dr. Markus Jahn
 * Email: jahn@signum-plus.at
 * Web: www.signum-plus.at
 * Date: 06/2015
 */

public class ProcessModelFactory {

    /**
     * eigene Beispiele für SESE
     */

    public static ProcessModel createBspOhneZerteilung() {
        return new ProcessModelModifier()
                .setId("BeispielOhneZerteilung")
                .setName("Beispiel Ohne Zerteilung")
                .setCreator("Stefanie")
                .setDescription("Testbeispiel für Modularisierung ohne Zerteilung")
                .setProcessUnitModel("Unit-1", new ProcessUnitModelModifier()
                        .setId("Unit-1")
                        .setName("Unit-1")
                        .addAuthorizedRole("Requester")
                        .setStartProcessStep("Entry Step")
                        .setProcessStepModel("Entry Step", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("Step 2")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("Step 2", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("Step 3")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )

                        .setProcessStepModel("Step 3", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("End Step")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )

                        .setProcessStepModel("End Step", new ProcessStepModelModifier()
                                .getProcessStepModel()
                        )
                        .getProcessUnitModel()
                )
                .getProcessModel();
    }

    public static ProcessModel createBspSeseEinfach() {
        return new ProcessModelModifier()
                .setId("BeispielSeseEinfach")
                .setName("Beispiel Sese Einfach")
                .setCreator("(aug)")
                .setDescription("Testbeispiel für Modularisierung Sese einfach")
                .setProcessUnitModel("Unit-1", new ProcessUnitModelModifier()
                        .setId("Unit-1")
                        .setName("Unit-1")
                        .addAuthorizedRole("Requester")
                        .setStartProcessStep("Entry Step")
                        .setProcessStepModel("Entry Step", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE Start")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE Start", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE left")
                                        .getProceedFunction()
                                )
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE right")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE left", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE END")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE right", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE END")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE END", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("End Step")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("End Step", new ProcessStepModelModifier()
                                .getProcessStepModel()
                        )
                        .getProcessUnitModel()
                )
                .getProcessModel();
    }

    public static ProcessModel createBspSeseVerschachtelt2End() {
        return new ProcessModelModifier()
                .setId("BeispielSeseVerschachtelt2End")
                .setName("Beispiel Sese Verschachtelt 2 End")
                .setCreator("aug")
                .setDescription("Testbeispiel für Modularisierung Sese 2 End Steps")
                .setProcessUnitModel("Unit-1", new ProcessUnitModelModifier()
                        .setId("Unit-1")
                        .setName("Unit-1")
                        .addAuthorizedRole("August")
                        .setStartProcessStep("Entry Step")
                        .setProcessStepModel("Entry Step", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("Step 2")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("Step 2", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 Start")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 Start", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 left")
                                        .getProceedFunction()
                                )
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 right, SESE 2 Start")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 right, SESE 2 Start", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 left")
                                        .getProceedFunction()
                                )
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 right")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 2 left", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 2 right", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 2 End", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 left", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 Step 1")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 Step 1", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 End", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("Step 3")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("Step 3", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("End Step 1")
                                        .getProceedFunction()
                                )
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("End Step 2")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("End Step 1", new ProcessStepModelModifier()
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("End Step 2", new ProcessStepModelModifier()
                                .getProcessStepModel()
                        )
                        .getProcessUnitModel()
                )
                .getProcessModel();
    }

    public static ProcessModel createBspSese2Start2Unit() {
        return new ProcessModelModifier()
                .setId("BeispielSese2Start2Unit")
                .setName("Beispiel Sese 2 Start 2 Unit")
                .setCreator("Stefanie")
                .setDescription("Testbeispiel für Modularisierung Sese 2 Starts 2 Units")

                //Unit 1
                .setProcessUnitModel("Unit-1", new ProcessUnitModelModifier()
                        .setStartProcessStep("Entry Step 1")
                        .setId("Unit-1")
                        .setName("Unit-1")
                        .addAuthorizedRole("PersonUnit1")

                        .setProcessStepModel("Entry Step 1", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("Step 2")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("Step 2", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 Start")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 Start", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 left")
                                        .getProceedFunction()
                                )
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 right, SESE 2 Start")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 right, SESE 2 Start", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 left")
                                        .getProceedFunction()
                                )
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 right")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 2 left", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 2 right", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 2 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 2 End", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 left", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 Step 1")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 Step 1", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("SESE 1 End")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("SESE 1 End", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("Step 3")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("Step 3", new ProcessStepModelModifier()
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("End Step 1")
                                        .getProceedFunction()
                                )
                                .addProcessFunction(new ProceedFunctionModifier()
                                        .setNext("End Step 2")
                                        .getProceedFunction()
                                )
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("End Step 1", new ProcessStepModelModifier()
                                .getProcessStepModel()
                        )
                        .setProcessStepModel("End Step 2", new ProcessStepModelModifier()
                                .getProcessStepModel()
                        )
                        .getProcessUnitModel()
                )
                .getProcessModel();
    }

 //   public static ProcessModel createBspSese_2start_2unit() {
    //      return new ProcessModelModifier()
 //               .setId("BeispielSese2start2unit")
   //             .setName("Beispiel Sese 2 Start 2 Unit")
     //           .setCreator("Stefanie")
       //         .setDescription("Testbeispiel für Modularisierung Sese 2 Start 2 Unit")
        //        .addAuthorizedStartRole("Stefanie")
          //      .setProcessUnitModel("Unit-1", new ProcessUnitModelModifier()
            //                    .setId("Unit-1")
              //                  .setName("Unit-1")
                //                .addAuthorizedRole("August")
                  //              .setStartProcessStep("Entry Step")
                    //            .setProcessStepModel("Entry Step", new ProcessStepModelModifier()
                      //                  .addProcessFunction(new ProceedFunctionModifier()
                        //                        .setNext("Step 2")
                          //                      .getProceedFunction()
                            //            )
                              //          .getProcessStepModel()
     //           )
   //             .getProcessModel();
//    }



    /**
     * eigene Beispiele SESE Ende
     */

  public static ProcessModel createCycleTest() {
    return new ProcessModelModifier()
            .setId("CycleTest")
            .setName("Cycle Test")
            .setCreator("FK")
            .setDescription("Testmodel for testing Cycles")
            .addAuthorizedStartRole("Requester")
            .setProcessUnitModel("Unit-1", new ProcessUnitModelModifier()
                    .setId("Unit-1")
                    .setName("Unit-1")
                    .addAuthorizedRole("Requester")
                    .setStartProcessStep("1")

                    //1
                    .setProcessStepModel("1", new ProcessStepModelModifier()
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("TestInput")
                                    .getRequestInputFunction()
                            )
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("2")
                                    .getProceedFunction()
                            ).setInputRequestModel("TestInput", new InputRequestModelModifier()
                                    .setSubject("1")
                                    .setContent(new FormModifier()
                                            .setHeader("1")
                                            .addInputResponseModel("Submit", new InputResponseModelModifier()
                                                    .setLabel("Submit")
                                                    .putValue("Submit", Bool.True)
                                                    .setResult(Result.Success)
                                                    .getInputResponseModel())

                                            .getForm()
                                    )
                                    .getInputRequestModel())
                            .getProcessStepModel()
                    )
                    //2
                    .setProcessStepModel("2", new ProcessStepModelModifier()
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("TestInput")
                                    .getRequestInputFunction()
                            )
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("3")
                                    .getProceedFunction()
                            ).setInputRequestModel("TestInput", new InputRequestModelModifier()
                                    .setSubject("2")
                                    .setContent(new FormModifier()
                                            .setHeader("2")
                                            .addInputResponseModel("Submit", new InputResponseModelModifier()
                                                    .setLabel("Submit")
                                                    .putValue("Submit", Bool.True)
                                                    .setResult(Result.Success)
                                                    .getInputResponseModel())

                                            .getForm()
                                    )
                                    .getInputRequestModel())
                            .getProcessStepModel()
                    )

                    //3
                    .setProcessStepModel("3", new ProcessStepModelModifier()
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("TestInput")
                                    .getRequestInputFunction()
                            )
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("1")
                                    .getProceedFunction()
                            )
                            .setInputRequestModel("TestInput", new InputRequestModelModifier()
                                    .setSubject("3")
                                    .setContent(new FormModifier()
                                            .setHeader("3")
                                            .addInputResponseModel("Submit", new InputResponseModelModifier()
                                                    .setLabel("Submit")
                                                    .putValue("Submit", Bool.True)
                                                    .setResult(Result.Success)
                                                    .getInputResponseModel())

                                            .getForm()
                                    )
                                    .getInputRequestModel())
                            .getProcessStepModel()
                    )
                    .getProcessUnitModel()).getProcessModel();
  }

  public static ProcessModel createFunctionalTest() {
    return new ProcessModelModifier()
            .setId("FunctionalTest")
            .setName("Functional Test")
            .setCreator("FK")
            .setDescription("Testing function-oriented Models")
            .addAuthorizedStartRole("Requester")

            //REQUESTER
            .setProcessUnitModel("Requester", new ProcessUnitModelModifier()
                            .setStartProcessStep("GetProductDescription")
                            .addAuthorizedRole("Requester")

                            .setProcessStepModel("GetProductDescription", new ProcessStepModelModifier()
                                    .setId("GetProductDescription")
                                    .setName("GetProductDescription")
                                    .addProcessFunction(new AssignUserFunctionModifier()
                                            .getAssignUserFunction())
                                    .addProcessFunction(new RequestInputFunctionModifier()
                                            .setModel("RequestProductDescription")
                                            .getRequestInputFunction())
                                    .addProcessFunction(new RequireFunctionModifier()
                                            .addValue("ProductDescription")
                                            .getRequireFunction())
                                    .addProcessFunction(new ProceedFunctionModifier()
//                    .setNext("<: return \"SendApprovalRequest\"; :>")
                                            .setTargetUnit("Approver")
                                            .setNext("CheckRequest")
//                    .setValue("ProductDescription")
                                            .addValue("ProductDescription", "<ProductDescription>")
                                            .getProceedFunction())
                                    .setInputRequestModel("RequestProductDescription", new InputRequestModelModifier()
                                            .setSubject("Request product description")
                                            .setContent(new FormModifier()
                                                    .setHeader("Please fill the product request:")
                                                    .addElement("Product", new RadioInput(new ListModifier<String>()
                                                            .add("Desktop")
                                                            .add("Notebook")
                                                            .getList()))
                                                    .addElement("Description", new TextInput())
                                                    .addElement("Accessories", new CheckboxInput(new ListModifier<String>()
                                                            .add("Keyboard")
                                                            .add("Mouse")
                                                            .add("Additional Charger")
                                                            .getList()))
                                                    .addElement("Manufacturer", new DropdownInput(new ListModifier<String>()
                                                            .add("Dell")
                                                            .add("Lenovo")
                                                            .add("Hewlett-Packard")
                                                            .getList()))
                                                    .addInputResponseModel("Accept", new InputResponseModelModifier()
                                                            .setLabel("Request Offer")
                                                            .setResult(Result.Success)
                                                            .putValue("ProductDescription", new MapModifier<>()
                                                                    .set("Product", "input:Product")
                                                                    .set("Description", "input:Description")
                                                                    .set("Accessories", "input:Accessories")
                                                                    .set("Manufacturer", "input:Manufacturer")
                                                                    .getMap())
                                                            .getInputResponseModel())
                                                    .addInputResponseModel("Discard", new InputResponseModelModifier()
                                                            .setResult(Result.Discard)
                                                            .setLabel("Discard")
                                                            .putValue("ProductDescription", DataItem.Null)
                                                            .getInputResponseModel())
                                                    .getForm())
                                            .getInputRequestModel())
                                    .getProcessStepModel())


                            .getProcessUnitModel()
            )

            //APPROVER
            .setProcessUnitModel("Approver", new ProcessUnitModelModifier()

                            .setProcessStepModel("CheckRequest", new ProcessStepModelModifier()
//                .addProcessFunction(new RequestUserFunctionModifier()
//                    .setRoleId("Approver")
//                    .setModel("RequestPurchaseApprover")
//                    .getRequestUserFunction())
                                    .addProcessFunction(new RequestInputFunctionModifier()
                                            .setModel("RequestPurchaseApprover")
                                            .getRequestInputFunction())
                                    .addProcessFunction(new RequireFunctionModifier()
                                            .addValue("IsApproved")
                                            .getRequireFunction())
                                    .addProcessFunction(new ProceedFunctionModifier()
                                            .setNext("SendApprovalResponse")
//                    .setValue("IsApproved")
                                            .addValue("IsApproved", "<IsApproved>")
                                            .getProceedFunction())
                                    .setInputRequestModel("RequestPurchaseApprover", new InputRequestModelModifier()
                                            .setSubject("Please approve the following purchase request")
                                            .setContent(new FormModifier()
                                                    .setHeader("Do you accept the user request for the following purchase approval?")
                                                    .addElement("Product", "<locals:ProductDescription.Product>")
                                                    .addElement("Description", "<locals:ProductDescription.Description>")
                                                    .addElement("Accessories", "<locals:ProductDescription.Accessories>")
                                                    .addElement("Manufacturer", "<locals:ProductDescription.Manufacturer>")
                                                    .addInputResponseModel("Approve", new InputResponseModelModifier()
                                                            .setResult(Result.Success)
                                                            .putValue("IsApproved", Bool.True)
                                                            .getInputResponseModel())
                                                    .addInputResponseModel("Refuse", new InputResponseModelModifier()
                                                            .setResult(Result.Success)
                                                            .setLabel("No way!")
                                                            .putValue("IsApproved", Bool.False)
                                                            .getInputResponseModel())
                                                    .addInputResponseModel("Discard", new InputResponseModelModifier()
                                                            .setResult(Result.Discard)
                                                            .setLabel("Discard")
                                                            .getInputResponseModel())
                                                    .getForm())
                                            .getInputRequestModel())
                                    .getProcessStepModel())

                            .getProcessUnitModel()
            )
            .getProcessModel();
  }


  public static ProcessModel createPurchaseProduct() {
    return new ProcessModelModifier()
            .setId("PurchaseProduct")
            .setName("Purchase Product")
            .setCreator("Markus Jahn")
            .setIsComplete(true)
            .setDescription("This is a demo process for presenting uFlow.")
            .addAuthorizedStartRole("Requester")

            .setProcessUnitModel("Requester", new ProcessUnitModelModifier()
                    .setStartProcessStep("GetProductDescription")
                    .addAuthorizedRole("Requester")

                    .setProcessStepModel("GetProductDescription", new ProcessStepModelModifier()
                            .setId("GetProductDescription")
                            .setName("GetProductDescription")
                            //.addProcessFunction(new AssignUserFunctionModifier()
                            //    .getAssignUserFunction())
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("RequestProductDescription")
                                    .getRequestInputFunction())
                            //.addProcessFunction(new RequireFunctionModifier()
                            //    .setValue("ProductDescription")
                            //    .getRequireFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
//                    .setNext("<: return \"SendApprovalRequest\"; :>")
                                    .setNext("SendApprovalRequest")
//                    .setValue("ProductDescription")
                                    .addValue("ProductDescription", "<locals:ProductDescription.Manufacturer>")
                                    .getProceedFunction())
                            .setInputRequestModel("RequestProductDescription", new InputRequestModelModifier()
                                    .setSubject("Product Description")
                                    .setContent(new FormModifier()
                                            .setHeader("Please fill the product request:")
                                            .addElement("Product", new RadioInput(new ListModifier<String>()
                                                    .add("Desktop")
                                                    .add("Notebook")
                                                    .getList()))
                                            .addElement("Description", new TextInput())
                                            .addElement("Accessories", new CheckboxInput(new ListModifier<String>()
                                                    .add("Keyboard")
                                                    .add("Mouse")
                                                    .add("Additional Charger")
                                                    .getList()))
                                            .addElement("Manufacturer", new DropdownInput(new ListModifier<String>()
                                                    .add("Dell")
                                                    .add("Lenovo")
                                                    .add("Hewlett-Packard")
                                                    .getList()))
                                            .addInputResponseModel("Accept", new InputResponseModelModifier()
                                                    .setLabel("Request Offer")
                                                    .setResult(Result.Success)
                                                    .putValue("ProductDescription", new MapModifier<>()
                                                            .set("Product", "input:Product")
                                                            .set("Description", "input:Description")
                                                            .set("Accessories", "input:Accessories")
                                                            .set("Manufacturer", "input:Manufacturer")
                                                            .getMap())
                                                    .getInputResponseModel())
                                            .addInputResponseModel("Discard", new InputResponseModelModifier()
                                                    .setResult(Result.Discard)
                                                    .setLabel("Discard")
                                                    .putValue("ProductDescription", DataItem.Null)
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())
                            .getProcessStepModel())

                    .setProcessStepModel("SendApprovalRequest", new ProcessStepModelModifier()
                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("Approver")
                                    .setLabel("Product Description")
//                    .setValue("ProductDescription")
                                    .setValue("ProductDescription", "<ProductDescription>")
                                    .getProvideFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("ReceiveApprovalResponse")
                                    .getProceedFunction())
                            .getProcessStepModel())

                    .setProcessStepModel("ReceiveApprovalResponse", new ProcessStepModelModifier()
                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("IsApproved")
                                    .getRequireFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
//                    .setNext("<: locals -> (boolean) locals.get(\"IsApproved\") ? \"BuyProduct\" : null :>")
                                    .setNext("BuyProduct")
                                    .setCondition("locals -> locals.get(\"IsApproved\")")
                                    .getProceedFunction())
                            .getProcessStepModel())

                    .setProcessStepModel("BuyProduct", new ProcessStepModelModifier()
                            .addProcessFunction(new CallFunctionModifier().setCode(
                                    "System.out.println(\"BuyProduct \"+locals);"
                            ).getCallFunction())
                            .getProcessStepModel())
                    .setProcessStepModel("BuyNotProduct", new ProcessStepModelModifier()
                            .addProcessFunction(new CallFunctionModifier().setCode(
                                    "System.out.println(\"BuynotProduct \"+locals);"
                            ).getCallFunction())
                            .getProcessStepModel())

                    .getProcessUnitModel())

            .setProcessUnitModel("Approver", new ProcessUnitModelModifier()
                    .setStartProcessStep("ReceiveApprovalRequest")
                    .addAuthorizedRole("Approver")

                    .setProcessStepModel("ReceiveApprovalRequest", new ProcessStepModelModifier()
                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("ProductDescription")
                                    .getRequireFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("ProcessApprovalRequest")
//                    .setValue("ProductDescription")
                                    .addValue("ProductDescription", "<ProductDescription>")
                                    .getProceedFunction())
                            .getProcessStepModel())

                    .setProcessStepModel("ProcessApprovalRequest", new ProcessStepModelModifier()
//                .addProcessFunction(new RequestUserFunctionModifier()
//                    .setRoleId("Approver")
//                    .setModel("RequestPurchaseApprover")
//                    .getRequestUserFunction())
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("RequestPurchaseApprover")
                                    .getRequestInputFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("SendApprovalResponse")
//                    .setValue("IsApproved")
                                    .addValue("IsApproved", "<IsApproved>")
                                    .getProceedFunction())
                            .setInputRequestModel("RequestPurchaseApprover", new InputRequestModelModifier()
                                    .setSubject("PurchaseRequestDecision")
                                    .setContent(new FormModifier()
                                            .setHeader("Do you accept the user request for the following purchase approval?")
                                            .addElement("Product", "<locals:ProductDescription.Product>")
                                            .addElement("Description", "<locals:ProductDescription.Description>")
                                            .addElement("Accessories", "<locals:ProductDescription.Accessories>")
                                            .addElement("Manufacturer", "<locals:ProductDescription>")
                                            .addInputResponseModel("Approve", new InputResponseModelModifier()
                                                    .setResult(Result.Success)
                                                    .putValue("IsApproved", Bool.True)
                                                    .getInputResponseModel())
                                            .addInputResponseModel("Refuse", new InputResponseModelModifier()
                                                    .setResult(Result.Success)
                                                    .setLabel("No way!")
                                                    .putValue("IsApproved", Bool.False)
                                                    .getInputResponseModel())
                                            .addInputResponseModel("Discard", new InputResponseModelModifier()
                                                    .setResult(Result.Discard)
                                                    .setLabel("Discard")
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())
                            .getProcessStepModel())

                    .setProcessStepModel("SendApprovalResponse", new ProcessStepModelModifier()
                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("Requester")
//                    .setValue("IsApproved")
                                    .setValue("IsApproved", "<IsApproved>")
                                    .getProvideFunction())
                            .getProcessStepModel())

                    .getProcessUnitModel())

            .getProcessModel();
  }

  public static ProcessModel createPurchaseProductExtended() {
    return new ProcessModelModifier()
            .setId("PurchaseProductExtended")
            .setName("Notebook Ordering")
            .setCreator("Florian Krenn")
            .setDescription("This is a demo process for presenting uFlow.")
            .addAuthorizedStartRole("Requester")

            //REQUESTER
            .setProcessUnitModel("Requester", new ProcessUnitModelModifier()
                    .setStartProcessStep("FillOutForm")
                    .addAuthorizedRole("Requester")

                    .setProcessStepModel("FillOutForm", new ProcessStepModelModifier()
                            .setId("FillOutForm")
                            .setName("Fill out Request Form")
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("RequestForm")
                                    .getRequestInputFunction())
                            .setInputRequestModel("RequestForm", new InputRequestModelModifier().getInputRequestModel())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("SendApprovalRequest")
                                    .addValue("RequestForm")
                                    .getProceedFunction())

                            .setInputRequestModel("RequestForm", new InputRequestModelModifier()
                                    .setSubject("Request Form")
                                    .setContent(new FormModifier()
                                            .setHeader("Please fill the oder request form:")
                                            .addElement("Product", new RadioInput(new ListModifier<String>()
                                                    .add("Desktop")
                                                    .add("Notebook")
                                                    .getList()))
                                            .addElement("Description", new TextInput())
                                            .addElement("Accessories", new CheckboxInput(new ListModifier<String>()
                                                    .add("Keyboard")
                                                    .add("Mouse")
                                                    .add("Additional Charger")
                                                    .getList()))
                                            .addElement("Manufacturer", new DropdownInput(new ListModifier<String>()
                                                    .add("Dell")
                                                    .add("Lenovo")
                                                    .add("Hewlett-Packard")
                                                    .getList()))
                                            .addInputResponseModel("Accept", new InputResponseModelModifier()
                                                    .setLabel("Request Offer")
                                                    .setResult(Result.Success)
                                                    .putValue("RequestForm", new MapModifier<>()
                                                            .set("Product", "input:Product")
                                                            .set("Description", "input:Description")
                                                            .set("Accessories", "input:Accessories")
                                                            .set("Manufacturer", "input:Manufacturer")
                                                            .getMap())
                                                    .getInputResponseModel())
                                            .addInputResponseModel("Discard", new InputResponseModelModifier()
                                                    .setResult(Result.Discard)
                                                    .setLabel("Discard")
                                                    .putValue("RequestForm", DataItem.Null)
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())

                            .getProcessStepModel())

                    .setProcessStepModel("SendApprovalRequest", new ProcessStepModelModifier()

                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("CostCenter")
//                    .setValue("ProductDescription")
                                    .setValue("RequestForm", "<RequestForm>")
                                    .getProvideFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("ReceiveApprovalResponse")
                                    .getProceedFunction())
                            .getProcessStepModel())

                    .setProcessStepModel("ReceiveApprovalResponse", new ProcessStepModelModifier()
                            .setName("Receive Feedback")
                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("Decision")
                                    .getRequireFunction())
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("ReviewDecision")
                                    .getRequestInputFunction())

                            .addProcessFunction(new CallFunctionModifier().setCode("System.out.println(locals);").getCallFunction())

                            .addProcessFunction(new ProceedFunctionModifier()
//                    .setNext("<: locals -> (boolean) locals.get(\"IsApproved\") ? \"BuyProduct\" : null :>")
                                    .setNext("OrderNewDevice")
                                    .setCondition("locals -> locals.get(\"Decision.IsApproved\")")
                                    .getProceedFunction())

                            .addProcessFunction(new RequireFunctionModifier()
                                    .setIsAlternative(true)
                                    .addValue("LetterOfIntent")
                                    .addValue("Absage")
                                    .getRequireFunction()
                            )

                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("A")
                                    .setCondition("locals -> locals.exists(\"LOI\")")
                                    .getProceedFunction())

                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("B")
                                    .setCondition("locals -> locals.exists(\"Absage\")")
                                    .getProceedFunction())

                            .setInputRequestModel("ReviewDecision", new InputRequestModelModifier()
                                    .setSubject("ReviewDecision")
                                    .setContent(new FormModifier()
                                            .setHeader("Decision for your Request was made")
                                            .addElement("Decision", "<locals:Decision.Result>")
                                            .addElement("Remark", "<locals:Decision.Remark>")
                                            .addInputResponseModel("Approve", new InputResponseModelModifier()
                                                    .setLabel("Accept")
                                                    .putValue("Test", "<locals:Decision.Remark>")
                                                    .setResult(Result.Success)
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())
                            .getProcessStepModel())

                    .setProcessStepModel("OrderNewDevice", new ProcessStepModelModifier()
                            .setName("Order New Device")
                            .getProcessStepModel())

                    .getProcessUnitModel())

            //HEAD OF DEPARTMENT
            .setProcessUnitModel("HeadOfDepartment", new ProcessUnitModelModifier()
                    .setStartProcessStep("ReceiveApprovalRequest")
                    .addAuthorizedRole("Approver")
                    .setName("Head of Department")

                    .setProcessStepModel("ReceiveApprovalRequest", new ProcessStepModelModifier()
                            .setName("Review Order Request")
                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("ProductInfo")
                                    .getRequireFunction())
                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("CostEstimate")
                                    .getRequireFunction())
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("ApproveRequest")
                                    .getRequestInputFunction()
                            )
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("SendApprovalResponse")
                                    .addValue("Decision")
                                    .getProceedFunction()
                            )


                            .setInputRequestModel("ApproveRequest", new InputRequestModelModifier()
                                    .setSubject("PurchaseRequestDecision")
                                    .setContent(new FormModifier()
                                            .setHeader("Do you accept the user request for the following purchase approval?")
                                            .addElement("Product", "<locals:ProductInfo.Product>")
                                            .addElement("Description", "<locals:ProductInfo.Description>")
                                            .addElement("Accessories", "<locals:ProductInfo.Accessories>")
                                            .addElement("Manufacturer", "<locals:ProductInfo.Manufacturer>")
                                            .addElement("CostEstimate", "<locals:CostEstimate>")
                                            .addElement("Remark", new TextInput())
                                            .addInputResponseModel("Approve", new InputResponseModelModifier()
                                                    .setResult(Result.Success)
                                                    .putValue("Decision", new MapModifier<>()
                                                            .set("IsApproved", Bool.True)
                                                            .set("Remark", "input:Remark")
                                                            .set("Result", "Accepted")
                                                            .getMap())
                                                    .getInputResponseModel())
                                            .addInputResponseModel("Refuse", new InputResponseModelModifier()
                                                    .setResult(Result.Success)
                                                    .setLabel("Refuse")
                                                    .putValue("Decision", new MapModifier<>()
                                                            .set("Result", "Denied")
                                                            .set("IsApproved", Bool.False)
                                                            .set("Remark", "input:Remark")
                                                            .getMap())
                                                    .getInputResponseModel())
                                            .addInputResponseModel("Discard", new InputResponseModelModifier()
                                                    .setResult(Result.Discard)
                                                    .setLabel("Discard")
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())
                            .getProcessStepModel())

                    .setProcessStepModel("SendApprovalResponse", new ProcessStepModelModifier()
                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("Requester")
                                    .setValue("Decision", "<Decision>")
                                    .getProvideFunction())

                            .getProcessStepModel())

                    .getProcessUnitModel())


            //COST CENTER
            .setProcessUnitModel("CostCenter", new ProcessUnitModelModifier()
                    .setStartProcessStep("ReceiveFinancialApprovalRequest")
                    .setName("Cost Center")
                    .addAuthorizedRole("Approver")

                    .setProcessStepModel("ReceiveFinancialApprovalRequest", new ProcessStepModelModifier()
                            .setName("Receive Order")

                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("RequestForm")
                                    .getRequireFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("CreateCostEstimate")
//                    .setValue("ProductDescription")
                                    .addValue("RequestForm", "<RequestForm>")
                                    .getProceedFunction())
                            .getProcessStepModel())

                    .setProcessStepModel("CreateCostEstimate", new ProcessStepModelModifier()
                            .setName("Create Cost Estimate")
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("CostEstimationForm")
                                    .getRequestInputFunction()
                            )
                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("HeadOfDepartment")
                                    .setValue("CostEstimate", "<CostEstimate>")
                                    .getProvideFunction())
                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("HeadOfDepartment")
                                    .setValue("ProductInfo", "<RequestForm>")
                                    .getProvideFunction())

                            .setInputRequestModel("CostEstimationForm", new InputRequestModelModifier()
                                    .setSubject("Product Description")
                                    .setContent(new FormModifier()
                                            .setHeader("Please Enter your cost estimate:")
                                            .setHeader("Do you accept the user request for the following purchase approval?")
                                            .addElement("Product", "<locals:RequestForm.Product>")
                                            .addElement("Description", "<locals:RequestForm.Description>")
                                            .addElement("Accessories", "<locals:RequestForm.Accessories>")
                                            .addElement("Manufacturer", "<locals:RequestForm.Manufacturer>")
                                            .addElement("CostEstimate", new TextInput())
                                            .addInputResponseModel("Confirm", new InputResponseModelModifier()
                                                    .setResult(Result.Success)
                                                    .putValue("CostEstimate", "input:CostEstimate")
                                                    .getInputResponseModel())
                                            .getForm()
                                    ).getInputRequestModel())
                            .getProcessStepModel())
                    .getProcessUnitModel())
            .getProcessModel();
  }

  public static ProcessModel createECSBDemoModel() {

    return new ProcessModelModifier()
            .setName("ECSB Demo")
            .setCreator("FK")
            .setDescription("A simple login process for presenting the ECSB integration")
            .addAuthorizedStartRole("Requester")

            .setProcessUnitModel("User", new ProcessUnitModelModifier()
                    .setStartProcessStep("EnterLoginData")
                    .setId("User")
                    .setName("User")
                    .addAuthorizedRole("User")

                    .setProcessStepModel("EnterLoginData", new ProcessStepModelModifier()
                            .setId("EnterLoginData")
                            .setName("Enter Login Data")

                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("EnterLoginData")
                                    .getRequestInputFunction())

                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("AuthenticationService")
                                    .setValue("LoginData", "<LoginData>")
                                    .getProvideFunction()
                            )
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("AwaitAuthResult")
                                    .getProceedFunction())
                            .setInputRequestModel("EnterLoginData", new InputRequestModelModifier()
                                    .setSubject("Enter Login Data")
                                    .setContent(new FormModifier()
                                            .setHeader("Please Enter Login Data")
                                            .addInputResponseModel("Submit", new InputResponseModelModifier()
                                                    .setLabel("Submit")
                                                    .putValue("Submit", Bool.True)
                                                    .setResult(Result.Success)
                                                    .getInputResponseModel())

                                            .getForm()
                                    )
                                    .getInputRequestModel())
                            .getProcessStepModel()
                    )

                    .setProcessStepModel("AwaitAuthResult", new ProcessStepModelModifier()
                            .setId("AwaitAuthResult")
                            .setName("Await Auth Result")
                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("AuthResult").getRequireFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .addValue("AuthResult")
                                    .setCondition("locals -> locals.get(\"AuthResult\").equals(\"Granted\")")
                                    .setNext("GrantAccess")
                                    .getProceedFunction()
                            )
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .addValue("AuthResult")
                                    .setCondition("locals -> !locals.get(\"AuthResult\").equals(\"Granted\")")
                                    .setNext("DenyAccess")
                                    .getProceedFunction()
                            )

                            .getProcessStepModel()
                    )

                    .setProcessStepModel("AccessGranted", new ProcessStepModelModifier()


                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("AcceptGranted")
                                    .getRequestInputFunction())
                            .addProcessFunction(new ProceedFunctionModifier().setNext((String) null).getProceedFunction())
                            .setInputRequestModel("AcceptGranted", new InputRequestModelModifier()
                                    .setContent(new FormModifier()
                                            .setHeader("Access Granted")
                                            .addInputResponseModel("Next", new InputResponseModelModifier()
                                                    .setLabel("Next")
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())
                            .getProcessStepModel())

                    .setProcessStepModel("AccessDenied", new ProcessStepModelModifier()
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("AcceptDenied")
                                    .getRequestInputFunction())
                            .addProcessFunction(new ProceedFunctionModifier().setNext((String) null).getProceedFunction())

                            .setInputRequestModel("AcceptDenied", new InputRequestModelModifier()

                                    .setContent(new FormModifier()
                                            .setHeader("Access Denied")
                                            .addInputResponseModel("Next", new InputResponseModelModifier()
                                                    .setLabel("Next")
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())
                            .getProcessStepModel())

                    .getProcessUnitModel())

            .setProcessUnitModel("AuthenticationService",
                    new ProcessUnitModelModifier()
                            .setId("AuthenticationService")
                            .setName("AuthenticationService")
                            .setStartProcessStep("CheckLoginData")
                            .addAuthorizedRole("AuthenticationService")


                            .setProcessStepModel("CheckLoginData", new ProcessStepModelModifier()
                                    .setId("CheckLoginData")
                                    .setName("Check Login Data")
                                    .addProcessFunction(new RequireFunctionModifier().addValue("LoginData").getRequireFunction())
                                    .addProcessFunction(new RequestInputFunctionModifier().
                                            setModel("CheckLoginData")
                                            .getRequestInputFunction())

                                    .addProcessFunction(new ProceedFunctionModifier()
                                            .addValue("AuthResult")
                                            .setNext("<: locals -> locals.get(\"AuthResult\").equals(\"Granted\") ? \"GrantAccess\" : \"DenyAccess\" :>")
                                            .getProceedFunction()
                                    )
                                    .setInputRequestModel("CheckLoginData", new InputRequestModelModifier()
                                            .setSubject("Check Login Data")
                                            .setContent(new FormModifier()
                                                    .setHeader("Check Login Data")
                                                    .addInputResponseModel("Grant", new InputResponseModelModifier()
                                                            .setResult(Result.Success)
                                                            .setLabel("Grant Access")
                                                            .putValue("AuthResult", "Granted")
                                                            .getInputResponseModel())
                                                    .addInputResponseModel("Deny", new InputResponseModelModifier()
                                                            .setResult(Result.Success)
                                                            .setLabel("Deny Access")
                                                            .putValue("AuthResult", "Denied")
                                                            .getInputResponseModel())

                                                    .getForm())


                                            .getInputRequestModel())
                                    .getProcessStepModel()
                            )

                            .setProcessStepModel("GrantAccess", new ProcessStepModelModifier()
                                    .setId("GrantAccess")
                                    .setName("Grant Access")
                                    .addProcessFunction(new RequestInputFunctionModifier().setModel("GrantAccess").getRequestInputFunction())
                                    .addProcessFunction(new ProvideFunctionModifier()
                                            .setValue("AuthResult", "<AuthResult>")
                                            .setTo("User")
                                            .getProvideFunction())
                                    .setInputRequestModel("GrantAccess", new InputRequestModelModifier()
                                            .setContent(new FormModifier()
                                                    .setHeader("Send Access Granted to User")
                                                    .addInputResponseModel("Send", new InputResponseModelModifier()
                                                            .setLabel("Send")
                                                            .putValue("Send", Bool.True)
                                                            .setResult(Result.Success)
                                                            .getInputResponseModel())
                                                    .getForm())
                                            .getInputRequestModel())

                                    .getProcessStepModel())

                            .setProcessStepModel("DenyAccess", new ProcessStepModelModifier()
                                    .setId("DenyAccess")
                                    .setName("DenyAccess")
                                    .addProcessFunction(new RequestInputFunctionModifier().setModel("DenyAccess").getRequestInputFunction())
                                    .addProcessFunction(new ProvideFunctionModifier()
                                            .setTo("User")
                                            .setValue("AuthResult", "<AuthResult>")
                                            .getProvideFunction())
                                    .setInputRequestModel("DenyAccess", new InputRequestModelModifier()
                                            .setContent(new FormModifier()
                                                    .setHeader("Send Access Denied to User")
                                                    .addInputResponseModel("Send", new InputResponseModelModifier()
                                                            .setLabel("Send")
                                                            .putValue("Send", Bool.True)
                                                            .setResult(Result.Success)
                                                            .getInputResponseModel())
                                                    .getForm())
                                            .getInputRequestModel())
                                    .getProcessStepModel())

                            .getProcessUnitModel()
            )

            .getProcessModel();

  }

  public static ProcessModel createECSBDemoModelWithBOs() {

    return new ProcessModelModifier()
            .setName("ECSB Demo With BOs")
            .setCreator("FK")
            .setDescription("A simple login process for presenting the ECSB integration")
            .addAuthorizedStartRole("Requester")

            .setProcessUnitModel("User", new ProcessUnitModelModifier()
                    .setStartProcessStep("EnterLoginData")
                    .setId("User")
                    .setName("User")
                    .addAuthorizedRole("User")

                    .setProcessStepModel("EnterLoginData", new ProcessStepModelModifier()
                            .setId("EnterLoginData")
                            .setName("Enter Login Data")

                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("EnterLoginData")
                                    .getRequestInputFunction())

                            .addProcessFunction(new ProvideFunctionModifier()
                                    .setTo("AuthenticationService")
                                    .setValue("LoginData", "<LoginData>")
                                    .getProvideFunction()
                            )
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("AwaitAuthResult")
                                    .getProceedFunction())

                            .setInputRequestModel("EnterLoginData", new InputRequestModelModifier()
                                    .setSubject("Enter Login Data")
                                    .setContent(new FormModifier()
                                            .setHeader("Please Enter Login Data")
                                            .addElement("UserName", new TextInput())
                                            .addElement("Password", new TextInput())
                                            .addInputResponseModel("Submit", new InputResponseModelModifier()
                                                    .setLabel("Submit")
                                                    .putValue("LoginData", new MapModifier()
                                                            .set("UserName", "input:UserName")
                                                            .set("Password", "input:Password")
                                                            .getMap()
                                                    )
                                                    .setResult(Result.Success)
                                                    .getInputResponseModel())

                                            .getForm()
                                    )
                                    .getInputRequestModel())

                            .getProcessStepModel()

                    )

                    .setProcessStepModel("AwaitAuthResult", new ProcessStepModelModifier()
                            .setId("AwaitAuthResult")
                            .setName("Await Auth Result")
                            .addProcessFunction(new RequireFunctionModifier()
                                    .addValue("AuthResult").getRequireFunction())
                            .addProcessFunction(new ProceedFunctionModifier()
                                    .setNext("<: locals -> locals.get(\"AuthResult\").equals(\"Granted\") ? \"AccessGranted\" : \"AccessDenied\" :>")
                                    .getProceedFunction()
                            )

                            .getProcessStepModel()
                    )

                    .setProcessStepModel("AccessGranted", new ProcessStepModelModifier()


                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("AcceptGranted")
                                    .getRequestInputFunction())
                            .addProcessFunction(new ProceedFunctionModifier().setNext((String) null).getProceedFunction())
                            .setInputRequestModel("AcceptGranted", new InputRequestModelModifier()
                                    .setContent(new FormModifier()
                                            .setHeader("Access Granted")
                                            .addInputResponseModel("Next", new InputResponseModelModifier()
                                                    .setLabel("Next")
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())

                            .getProcessStepModel())

                    .setProcessStepModel("AccessDenied", new ProcessStepModelModifier()
                            .addProcessFunction(new RequestInputFunctionModifier()
                                    .setModel("AcceptDenied")
                                    .getRequestInputFunction())
                            .addProcessFunction(new ProceedFunctionModifier().setNext((String) null).getProceedFunction())
                            .setInputRequestModel("AcceptDenied", new InputRequestModelModifier()

                                    .setContent(new FormModifier()
                                            .setHeader("Access Denied")
                                            .addInputResponseModel("Next", new InputResponseModelModifier()
                                                    .setLabel("Next")
                                                    .getInputResponseModel())
                                            .getForm())
                                    .getInputRequestModel())
                            .getProcessStepModel())

                    .getProcessUnitModel())

            .setProcessUnitModel("AuthenticationService",
                    new ProcessUnitModelModifier()
                            .setId("AuthenticationService")
                            .setName("AuthenticationService")
                            .setStartProcessStep("CheckLoginData")
                            .addAuthorizedRole("AuthenticationService")


                            .setProcessStepModel("CheckLoginData", new ProcessStepModelModifier()
                                    .setId("CheckLoginData")
                                    .setName("Check Login Data")
                                    .addProcessFunction(new RequireFunctionModifier().addValue("LoginData").getRequireFunction())
                                    .addProcessFunction(new RequestInputFunctionModifier().
                                            setModel("CheckLoginData")
                                            .getRequestInputFunction())

                                    .addProcessFunction(new ProceedFunctionModifier()
                                            .addValue("AuthResult")
                                            .setCondition("locals -> locals.get(\"AuthResult\").equals(\"Granted\")")
                                            .setNext("GrantAccess")
                                            .getProceedFunction()
                                    )
                                    .addProcessFunction(new ProceedFunctionModifier()
                                            .addValue("AuthResult")
                                            .setCondition("locals -> !locals.get(\"AuthResult\").equals(\"Granted\")")
                                            .setNext("DenyAccess")
                                            .getProceedFunction()
                                    )
                                    .setInputRequestModel("CheckLoginData", new InputRequestModelModifier()
                                            .setSubject("Check Login Data")
                                            .setContent(new FormModifier()
                                                    .setHeader("Check Login Data")
                                                    .addElement("UserName", "<locals:LoginData.UserName>")
                                                    .addElement("Password", "<locals:LoginData.Password>")
                                                    .addElement("Expected Password", "pwd")
                                                    .addInputResponseModel("Grant", new InputResponseModelModifier()
                                                            .setResult(Result.Success)
                                                            .setLabel("Grant Access")
                                                            .putValue("AuthResult", "Granted")
                                                            .getInputResponseModel())
                                                    .addInputResponseModel("Deny", new InputResponseModelModifier()
                                                            .setResult(Result.Success)
                                                            .setLabel("Deny Access")
                                                            .putValue("AuthResult", "Denied")
                                                            .getInputResponseModel())

                                                    .getForm())


                                            .getInputRequestModel())

                                    .getProcessStepModel()
                            )

                            .setProcessStepModel("GrantAccess", new ProcessStepModelModifier()
                                    .setId("GrantAccess")
                                    .setName("Grant Access")
                                    .addProcessFunction(new RequestInputFunctionModifier().setModel("GrantAccess").getRequestInputFunction())
                                    .addProcessFunction(new ProvideFunctionModifier()
                                            .setValue("AuthResult", "<AuthResult>")
                                            .setTo("User")
                                            .getProvideFunction())
                                    .setInputRequestModel("GrantAccess", new InputRequestModelModifier()
                                            .setContent(new FormModifier()
                                                    .setHeader("Send Access Granted to User")
                                                    .addInputResponseModel("Send", new InputResponseModelModifier()
                                                            .setLabel("Send")
                                                            .putValue("Send", Bool.True)
                                                            .setResult(Result.Success)
                                                            .getInputResponseModel())
                                                    .getForm())
                                            .getInputRequestModel())

                                    .getProcessStepModel())

                            .setProcessStepModel("DenyAccess", new ProcessStepModelModifier()
                                    .setId("DenyAccess")
                                    .setName("DenyAccess")
                                    .addProcessFunction(new RequestInputFunctionModifier().setModel("DenyAccess").getRequestInputFunction())
                                    .addProcessFunction(new ProvideFunctionModifier()
                                            .setTo("User")
                                            .setValue("AuthResult", "<AuthResult>")
                                            .getProvideFunction())
                                    .setInputRequestModel("DenyAccess", new InputRequestModelModifier()
                                            .setContent(new FormModifier()
                                                    .setHeader("Send Access Denied to User")
                                                    .addInputResponseModel("Send", new InputResponseModelModifier()
                                                            .setLabel("Send")
                                                            .putValue("Send", Bool.True)
                                                            .setResult(Result.Success)
                                                            .getInputResponseModel())
                                                    .getForm())
                                            .getInputRequestModel())

                                    .getProcessStepModel())

                            .getProcessUnitModel()
            )

            .getProcessModel();

  }

  }
